services:
  unraid-management-agent-dev:
    platform: linux/amd64
    image: unraid-management-agent-dev
    container_name: unraid-management-agent-dev
    user: vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        GO_VERSION: 1.24.0
        NODE_VERSION: 20
    volumes:
      - ..:/workspaces/unraid-management-agent:cached
    init: true
    tty: true
